# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'background.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_backgroundMainWindow(object):
    def setupUi(self, backgroundMainWindow):
        backgroundMainWindow.setObjectName("backgroundMainWindow")
        backgroundMainWindow.resize(632, 320)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        backgroundMainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../AppData/Roaming/eliasbenb/EzSetup/images/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        backgroundMainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(backgroundMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.browsePushButton = QtWidgets.QPushButton(self.centralwidget)
        self.browsePushButton.setGeometry(QtCore.QRect(471, 38, 80, 23))
        self.browsePushButton.setObjectName("browsePushButton")
        self.pathLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.pathLineEdit.setGeometry(QtCore.QRect(89, 40, 361, 20))
        self.pathLineEdit.setReadOnly(True)
        self.pathLineEdit.setObjectName("pathLineEdit")
        self.leftLine = QtWidgets.QFrame(self.centralwidget)
        self.leftLine.setGeometry(QtCore.QRect(81, 90, 20, 200))
        self.leftLine.setFrameShadow(QtWidgets.QFrame.Plain)
        self.leftLine.setLineWidth(1)
        self.leftLine.setFrameShape(QtWidgets.QFrame.VLine)
        self.leftLine.setObjectName("leftLine")
        self.rightLine = QtWidgets.QFrame(self.centralwidget)
        self.rightLine.setGeometry(QtCore.QRect(439, 90, 20, 200))
        self.rightLine.setFrameShadow(QtWidgets.QFrame.Plain)
        self.rightLine.setLineWidth(1)
        self.rightLine.setFrameShape(QtWidgets.QFrame.VLine)
        self.rightLine.setObjectName("rightLine")
        self.topLine = QtWidgets.QFrame(self.centralwidget)
        self.topLine.setGeometry(QtCore.QRect(90, 81, 360, 16))
        self.topLine.setFrameShadow(QtWidgets.QFrame.Plain)
        self.topLine.setLineWidth(1)
        self.topLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.topLine.setObjectName("topLine")
        self.bottomLine = QtWidgets.QFrame(self.centralwidget)
        self.bottomLine.setGeometry(QtCore.QRect(90, 281, 360, 16))
        self.bottomLine.setFrameShadow(QtWidgets.QFrame.Plain)
        self.bottomLine.setLineWidth(1)
        self.bottomLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.bottomLine.setObjectName("bottomLine")
        self.backgroundLabel = QtWidgets.QLabel(self.centralwidget)
        self.backgroundLabel.setGeometry(QtCore.QRect(92, 90, 357, 201))
        self.backgroundLabel.setText("")
        self.backgroundLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.backgroundLabel.setObjectName("backgroundLabel")
        backgroundMainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(backgroundMainWindow)
        QtCore.QMetaObject.connectSlotsByName(backgroundMainWindow)

    def retranslateUi(self, backgroundMainWindow):
        _translate = QtCore.QCoreApplication.translate
        backgroundMainWindow.setWindowTitle(_translate("backgroundMainWindow", "EzSetup - Background"))
        self.browsePushButton.setText(_translate("backgroundMainWindow", "Browse"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    backgroundMainWindow = QtWidgets.QMainWindow()
    ui = Ui_backgroundMainWindow()
    ui.setupUi(backgroundMainWindow)
    backgroundMainWindow.show()
    sys.exit(app.exec_())
