# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QtDesigner\home.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_homeMainWindow(object):
    def setupUi(self, homeMainWindow):
        homeMainWindow.setObjectName("homeMainWindow")
        homeMainWindow.resize(800, 233)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        homeMainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("QtDesigner\\../../../../AppData/Roaming/eliasbenb/EzSetup/images/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        homeMainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(homeMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.backgroundPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.backgroundPushButton.setGeometry(QtCore.QRect(-1, 0, 201, 131))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.backgroundPushButton.setFont(font)
        self.backgroundPushButton.setObjectName("backgroundPushButton")
        self.filesPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.filesPushButton.setGeometry(QtCore.QRect(200, 0, 200, 131))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.filesPushButton.setFont(font)
        self.filesPushButton.setObjectName("filesPushButton")
        self.fontsPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.fontsPushButton.setGeometry(QtCore.QRect(400, 0, 200, 131))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.fontsPushButton.setFont(font)
        self.fontsPushButton.setObjectName("fontsPushButton")
        self.softwarePushButton = QtWidgets.QPushButton(self.centralwidget)
        self.softwarePushButton.setGeometry(QtCore.QRect(600, 0, 201, 131))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.softwarePushButton.setFont(font)
        self.softwarePushButton.setObjectName("softwarePushButton")
        self.setupPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.setupPushButton.setGeometry(QtCore.QRect(0, 130, 801, 81))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.setupPushButton.setFont(font)
        self.setupPushButton.setObjectName("setupPushButton")
        homeMainWindow.setCentralWidget(self.centralwidget)
        self.MenuBar = QtWidgets.QMenuBar(homeMainWindow)
        self.MenuBar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.MenuBar.setObjectName("MenuBar")
        self.fileMenu = QtWidgets.QMenu(self.MenuBar)
        self.fileMenu.setObjectName("fileMenu")
        self.helpMenu = QtWidgets.QMenu(self.MenuBar)
        self.helpMenu.setObjectName("helpMenu")
        homeMainWindow.setMenuBar(self.MenuBar)
        self.importAction = QtWidgets.QAction(homeMainWindow)
        self.importAction.setObjectName("importAction")
        self.exportAction = QtWidgets.QAction(homeMainWindow)
        self.exportAction.setObjectName("exportAction")
        self.github_repositryAction = QtWidgets.QAction(homeMainWindow)
        self.github_repositryAction.setObjectName("github_repositryAction")
        self.fileMenu.addAction(self.importAction)
        self.fileMenu.addAction(self.exportAction)
        self.helpMenu.addAction(self.github_repositryAction)
        self.MenuBar.addAction(self.fileMenu.menuAction())
        self.MenuBar.addAction(self.helpMenu.menuAction())

        self.retranslateUi(homeMainWindow)
        QtCore.QMetaObject.connectSlotsByName(homeMainWindow)

    def retranslateUi(self, homeMainWindow):
        _translate = QtCore.QCoreApplication.translate
        homeMainWindow.setWindowTitle(_translate("homeMainWindow", "EzSetup"))
        self.backgroundPushButton.setText(_translate("homeMainWindow", "Background"))
        self.filesPushButton.setText(_translate("homeMainWindow", "Files"))
        self.fontsPushButton.setText(_translate("homeMainWindow", "Fonts"))
        self.softwarePushButton.setText(_translate("homeMainWindow", "Software"))
        self.setupPushButton.setText(_translate("homeMainWindow", "Setup"))
        self.fileMenu.setTitle(_translate("homeMainWindow", "File"))
        self.helpMenu.setTitle(_translate("homeMainWindow", "Help"))
        self.importAction.setText(_translate("homeMainWindow", "Import"))
        self.exportAction.setText(_translate("homeMainWindow", "Export"))
        self.github_repositryAction.setText(_translate("homeMainWindow", "GitHub Repositry"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    homeMainWindow = QtWidgets.QMainWindow()
    ui = Ui_homeMainWindow()
    ui.setupUi(homeMainWindow)
    homeMainWindow.show()
    sys.exit(app.exec_())
